version: '3.8'

services:
  # Aplicación principal
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env.local
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - delfin-network

  # Worker para procesar colas
  worker:
    build: .
    command: node worker.js
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env.local
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - delfin-network

  # Redis para colas de trabajo
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - delfin-network
    command: redis-server --appendonly yes

  # Nginx como proxy inverso (opcional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - delfin-network

volumes:
  redis_data:

networks:
  delfin-network:
    driver: bridge
